apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: blog
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: onurinc/apigateway:v1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway
  namespace: blog
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 40
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: blog
spec:
  selector:
    app: api-gateway
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engagements-api
  namespace: blog
  labels:
    app: engagements-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engagements-api
  template:
    metadata:
      labels:
        app: engagements-api
    spec:
      containers:
        - name: engagements-api
          image: onurinc/engagementsapi:v1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: DB_HOST
              value: engagements-db
            - name: DB_NAME
              value: engagements
            - name: DB_SA_PASSWORD
              value: password1!
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: engagements-api
  namespace: blog
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: engagements-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 40
---
apiVersion: v1
kind: Service
metadata:
  name: engagementsapi
  namespace: blog
spec:
  selector:
    app: engagements-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engagements-db
  namespace: blog
  labels:
    app: engagements-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engagements-db
  template:
    metadata:
      labels:
        app: engagements-db
    spec:
      containers:
        - name: engagements-db
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          resources:
            requests:
              cpu: 100m
              memory: 2G
            limits:
              cpu: 100m
              memory: 2G
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: password1!
---
apiVersion: v1
kind: Service
metadata:
  name: engagements-db
  namespace: blog
spec:
  selector:
    app: engagements-db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersystem-api
  namespace: blog
  labels:
    app: usersystem-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usersystem-api
  template:
    metadata:
      labels:
        app: usersystem-api
    spec:
      containers:
        - name: usersystem-api
          image: onurinc/usersystemapi:v1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: DB_HOST
              value: usersystem-db
            - name: DB_NAME
              value: usersystem
            - name: DB_SA_PASSWORD
              value: password1!
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: usersystem-api
  namespace: blog
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: usersystem-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 40
---
apiVersion: v1
kind: Service
metadata:
  name: usersystemapi
  namespace: blog
spec:
  selector:
    app: usersystem-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersystem-db
  namespace: blog
  labels:
    app: usersystem-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usersystem-db
  template:
    metadata:
      labels:
        app: usersystem-db
    spec:
      containers:
        - name: usersystem-db
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          resources:
            requests:
              cpu: 100m
              memory: 2G
            limits:
              cpu: 100m
              memory: 2G
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: password1!
---
apiVersion: v1
kind: Service
metadata:
  name: usersystem-db
  namespace: blog
spec:
  selector:
    app: usersystem-db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-api
  namespace: blog
  labels:
    app: blog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-api
  template:
    metadata:
      labels:
        app: blog-api
    spec:
      containers:
        - name: blog-api
          image: onurinc/blogapi:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "User ID=postgres;Password=postgres;Server=blogdb;Port=5432;Database=ITBlogDb; IntegratedSecurity=true;Pooling=true;"
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: blog-api
  namespace: blog
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blog-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: blogapi
  namespace: blog
spec:
  selector:
    app: blog-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-db
  namespace: blog
  labels:
    app: blog-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-db
  template:
    metadata:
      labels:
        app: blog-db
    spec:
      containers:
        - name: blog-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 50Mi
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: ITBlogDb
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: blog-db-autoscaler
  namespace: blog
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blog-db
  minReplicas: 1 # Minimum number of replicas
  maxReplicas: 5 # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 2 # Target average CPU utilization in percentage
---
apiVersion: v1
kind: Service
metadata:
  name: blogdb
  namespace: blog
spec:
  selector:
    app: blog-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
