apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogapi-deployment
  annotations:
    kubernetes.io/change-cause: "initial deployment of the blogapi"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: blogapi
  template:
    metadata:
      name: myblogapi
      labels:
        env: prod
        app: blogapi
        app.kubernetes.io/name: blogapi
    spec:
      containers:
        - name: blogapi
          image: onurinc/blogapi
          ports:
            - containerPort: 80
              name: http-web-api
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80

apiVersion: v1
kind: Service
metadata:
  name: blog-api-lb-service
spec:
  selector:
    app.kubernetes.io/name: blogapi
  ports:
    - name: blogapi-port
      protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer